"""Build identity.html, a review page with every generated asset inlined."""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
SVG = os.path.join(HERE, 'svg')

SHEET = [
    ('The wordmark', 'No symbol. The letters are built on a square grid with a '
     'two-unit stroke, which is the shape of a terminal and the shape of a bar. '
     'One drawing, one file, nothing to keep in sync.',
     [('brig-lockup-on-dark', 'dark'), ('hull-lockup-on-dark', 'dark'),
      ('brig-lockup-on-light', 'light'), ('hull-lockup-on-light', 'light')]),
    ('The avatar', 'Where the wordmark will not fit, the first letter stands '
     'alone on a navy square. GitHub rounds the corners, so the file carries '
     'none.',
     [('brig-avatar', 'plain'), ('hull-avatar', 'plain')]),
    ('The mark alone', 'The same letter with the field taken away, for placing '
     'on a background you control.',
     [('brig-mark-on-dark', 'dark'), ('hull-mark-on-dark', 'dark'),
      ('brig-mark-on-light', 'light'), ('hull-mark-on-light', 'light')]),
    ('The badge', 'The wordmark on its own navy field, with four units of clear '
     'space baked in, for slides and anywhere the background is out of our hands.',
     [('brig-lockup-badge', 'plain')]),
]

SIZES = [110, 66, 44, 33, 22]
AVATARS = [96, 64, 32, 16]

CSS = """
:root { color-scheme: light dark; }
body { margin: 0; padding: 48px 32px 96px; background: #F2EFE6; color: #0E2233;
       font: 15px/1.6 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; }
main { max-width: 900px; margin: 0 auto; }
h1 { font-size: 34px; letter-spacing: -0.03em; margin: 0 0 4px; }
h2 { font-size: 20px; letter-spacing: -0.02em; margin: 56px 0 6px;
     padding-top: 18px; border-top: 1px solid rgba(14,34,51,0.18); }
p { margin: 0 0 20px; max-width: 62ch; color: rgba(14,34,51,0.78); }
.row { display: flex; flex-wrap: wrap; gap: 20px; align-items: flex-end; }
.tile { padding: 24px; border-radius: 10px; }
.tile.dark { background: #0E2233; }
.tile.light { background: #FFFFFF; border: 1px solid rgba(14,34,51,0.14); }
.tile.plain { padding: 0; }
.tile svg { display: block; }
.cap { margin: 8px 0 0; font-size: 12px; color: rgba(14,34,51,0.6); }
.ladder { display: flex; flex-wrap: wrap; gap: 28px; align-items: flex-end;
          background: #0E2233; padding: 28px; border-radius: 10px; }
.ladder .cap { color: rgba(242,239,230,0.6); }
"""


def load(name, height=None, width=None):
    with open(os.path.join(SVG, '%s.svg' % name)) as f:
        s = f.read()
    s = re.sub(r'<title>.*?</title>', '', s, flags=re.S)
    if height:
        s = re.sub(r'width="\d+" height="\d+"',
                   'height="%d"' % height, s, count=1)
    elif width:
        s = re.sub(r'width="\d+" height="\d+"',
                   'width="%d"' % width, s, count=1)
    return s.strip()


out = ['<!doctype html>', '<html lang="en"><head><meta charset="utf-8">',
       '<meta name="viewport" content="width=device-width,initial-scale=1">',
       '<title>brig / hull identity</title><style>%s</style></head><body><main>'
       % CSS,
       '<h1>brig / hull identity</h1>',
       '<p>Generated by <code>build.sh</code>. Every file below is inlined from '
       '<code>svg/</code>, so what renders here is what ships.</p>']

for title, blurb, items in SHEET:
    out.append('<h2>%s</h2><p>%s</p><div class="row">' % (title, blurb))
    for name, tone in items:
        h = 44 if name.endswith(('on-dark', 'on-light')) and 'lockup' in name else 96
        out.append('<div><div class="tile %s">%s</div><p class="cap">%s.svg</p>'
                   '</div>' % (tone, load(name, height=h), name))
    out.append('</div>')

out.append('<h2>Size</h2><p>The wordmark holds down to about 33&nbsp;px tall. '
           'Below that the stroke falls under two device pixels and the '
           'counters close up. Use the avatar instead.</p><div class="ladder">')
for s in SIZES:
    out.append('<div>%s<p class="cap">%d px</p></div>'
               % (load('brig-lockup-on-dark', height=s), s))
out.append('</div>')

out.append('<h2>The avatar, down to 16&nbsp;px</h2><p>The glyph is legible at '
           'every size GitHub renders.</p><div class="row">')
for s in AVATARS:
    out.append('<div><div class="tile plain">%s</div><p class="cap">%d</p></div>'
               % (load('brig-avatar', width=s), s))
out.append('</div></main></body></html>')

with open(os.path.join(HERE, 'identity.html'), 'w') as f:
    f.write('\n'.join(out) + '\n')
print('wrote identity.html')
